### ISSUE TITLE
Lock when TX line to SDS is cut

### ISSUE THREAD

**Issue by netmaniac** [dok-net/esp_sds011#6]
Hi
I have noticed blocking issue in `_read_response` in case when TX line from ESP to SDS is being cut/disconnected. After power on SDS011 with factory settings will send readings. `_read_response` will block in such case. Response format is different than data frame format and code execution will be blocked by switch command https://github.com/dok-net/esp_sds011/blob/master/src/Sds011.cpp#L200 

I guess that it will happen also when to serial will be attached other device than SDS011 which will be sending data stream not matching frame format expected by `_read_response`.

I guess there should be some kind of global timeout, not only per byte to avoid ESP from being totally unresponsive in such case.

**Comment by dok-net** [comment]
@netmaniac Please verify the fix.
